on:
  push:
    branches:
      - develop

name: auto-dev-version

jobs:
  auto-dev-version:
    if: github.repository == 'fbenke-pik/remind'
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true
          configFilePath: .github/GitVersion.yml

      - name: Update CITATION.cff and config/default.cfg with version and date
        run: |
          sed -i 's/^version:.*$/version: "${{ steps.gitversion.outputs.assemblySemVer }}"/' CITATION.cff
          sed -i "s/^date-released:.*$/date-released: $(date --iso)/" CITATION.cff
          sed -i 's/^cfg$model_version <-.*$/cfg$model_version <- "${{ steps.gitversion.outputs.assemblySemVer }}"/' config/default.cfg

      - name: Commit changes to CITATION.cff
        uses: EndBug/add-and-commit@v9
        with:
          add: '["CITATION.cff", "config/default.cfg"]'
          author_name: REMIND Research Software Engineering
          author_email: rse@pik-potsdam.de
          message: 'Release development version ${{ steps.gitversion.outputs.assemblySemVer }}'
          tag: 'v${{ steps.gitversion.outputs.assemblySemVer }}'
          pathspec_error_handling: exitImmediately
